# Generated by Django 5.2 on 2025-05-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_book_alter_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="rating",
        ),
    ]
